### ISSUE TITLE
Withdrawal issue

### ISSUE THREAD

**Issue by Sachinat** [valderosch/atom-cloud-storage#2]
![Screenshot_2024-01-12-23-00-20-356_com android chrome](https://github.com/valderosch/atom-cloud-storage/assets/156459185/5c55f0cb-e4da-4d85-83be-2dd4153d9c53)

While I tried to withdrawal in  pondanec. Online there is showing insufficient gas fund what is the meaning of this I have USDT  in this wallet how can i withdrawal this amount

**Comment by valderosch** [comment]
What?

**Comment by Sachinat** [comment]
> What?

Did u got the above what I said??

**Comment by valderosch** [comment]
how your issue relates to my repository?
